export const UnitList = [
  { value: "m", label: "meter (m)" },
  { value: "m2", label: "meter persegi (m²)" },
  { value: "m3", label: "meter kubik (m³)" },
  { value: "kg", label: "kilogram (kg)" },
  { value: "ton", label: "ton" },
  { value: "liter", label: "liter" },
  { value: "buah", label: "buah" },
  { value: "unit", label: "unit" },
  { value: "pasang", label: "pasang" },
  { value: "lembar", label: "lembar" },
  { value: "roll", label: "roll" },
  { value: "hari", label: "hari" },
  { value: "jam", label: "jam" },
  { value: "orang", label: "orang" },
  { value: "ls", label: "lumpsum (ls)" },
  { value: "pkg", label: "package (pkg)" },
  { value: "set", label: "set" },
  { value: "btg", label: "batang (btg)" },
  { value: "zak", label: "zak" },
  { value: "dus", label: "dus" },
  { value: "kodi", label: "kodi" },
  { value: "rim", label: "rim" },
  { value: "galon", label: "galon" },
  { value: "kotak", label: "kotak" },
];